# Generated by Django 6.0.1 on 2026-01-08 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField(help_text='Número de piso (-1 para sótano)')),
                ('tipo', models.CharField(choices=[('aula_teorica', 'Aula Teórica'), ('lab_computo', 'Laboratorio de Cómputo'), ('lab_especializado', 'Laboratorio Especializado'), ('administrativo', 'Administrativo')], max_length=30)),
                ('nombre', models.CharField(help_text='Ej: Lab. Química, Aula 101', max_length=200)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('capacidad', models.IntegerField(blank=True, help_text='Capacidad del ambiente', null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['pabellon', 'piso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('sistemas', 'Sistemas'), ('operaciones', 'Operaciones'), ('laboratorio', 'Laboratorio')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Ej: CLN, CLS', max_length=10, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: A, B, C, Principal', max_length=50)),
                ('pisos', models.IntegerField(default=1, help_text='Número total de pisos')),
                ('tiene_sotano', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pabellón',
                'verbose_name_plural': 'Pabellones',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_utp', models.CharField(help_text='Código único UTP (ej: SIS-2026-0001)', max_length=50, unique=True)),
                ('serie', models.CharField(help_text='Número de serie del fabricante', max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('instalado', 'Instalado'), ('dañado', 'Dañado'), ('obsoleto', 'Obsoleto')], default='nuevo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_adquisicion', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de adquisición', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('garantia_hasta', models.DateField(blank=True, help_text='Fecha de vencimiento de garantía', null=True)),
                ('es_leasing', models.BooleanField(default=False)),
                ('leasing_empresa', models.CharField(blank=True, max_length=200)),
                ('leasing_contrato', models.CharField(blank=True, max_length=100)),
                ('leasing_vencimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='productos.ambiente', verbose_name='Ubicación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='productos.area')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_modificados', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(blank=True, help_text='Usuario que actualmente tiene asignado el ítem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='productos.item')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesSistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('procesador', models.CharField(blank=True, help_text='Ej: Intel Core i7-1365U', max_length=200)),
                ('generacion_procesador', models.CharField(blank=True, help_text='Ej: 13va Generación', max_length=50)),
                ('ram_total_gb', models.IntegerField(blank=True, help_text='Total en GB', null=True)),
                ('ram_configuracion', models.CharField(blank=True, help_text='Ej: 2x8GB, 1x16GB', max_length=50)),
                ('ram_tipo', models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('almacenamiento_gb', models.IntegerField(blank=True, help_text='Capacidad en GB', null=True)),
                ('almacenamiento_tipo', models.CharField(blank=True, choices=[('HDD', 'HDD (Disco Duro)'), ('SSD', 'SSD SATA'), ('NVMe', 'SSD NVMe'), ('eMMC', 'eMMC')], max_length=10)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones_sistemas', to='productos.item')),
            ],
            options={
                'verbose_name': 'Especificaciones de Sistemas',
                'verbose_name_plural': 'Especificaciones de Sistemas',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('traslado', 'Traslado'), ('cambio_estado', 'Cambio de Estado'), ('asignacion', 'Asignación de Usuario'), ('entrada', 'Entrada al Inventario'), ('baja', 'Baja del Inventario'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('ejecutado', 'Ejecutado'), ('ejecutado_emergencia', 'Ejecutado (Emergencia)'), ('revertido', 'Revertido')], default='pendiente', max_length=25)),
                ('es_emergencia', models.BooleanField(default=False)),
                ('estado_item_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_item_nuevo', models.CharField(blank=True, max_length=20)),
                ('motivo', models.TextField(help_text='Razón del movimiento')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='movimientos/%Y/%m/')),
                ('notas_evidencia', models.TextField(blank=True)),
                ('escalado', models.BooleanField(default=False)),
                ('fecha_escalamiento', models.DateTimeField(blank=True, null=True)),
                ('ambiente_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='productos.ambiente', verbose_name='Ubicación destino')),
                ('ambiente_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='productos.ambiente', verbose_name='Ubicación origen')),
                ('autorizado_por', models.ForeignKey(help_text='Supervisor que debe aprobar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('escalado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_escalados', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.item')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('usuario_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_usuario_anterior', to=settings.AUTH_USER_MODEL)),
                ('usuario_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_usuario_nuevo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud', 'Nueva Solicitud'), ('emergencia', 'Movimiento de Emergencia'), ('aprobado', 'Solicitud Aprobada'), ('rechazado', 'Solicitud Rechazada'), ('recordatorio', 'Recordatorio'), ('escalamiento', 'Escalamiento'), ('garantia', 'Alerta de Garantía')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('url', models.CharField(blank=True, help_text='URL de destino', max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('urgente', models.BooleanField(default=False)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='productos.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='ambiente',
            name='pabellon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambientes', to='productos.pabellon'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('operador', 'Operador'), ('externo', 'Externo')], default='operador', max_length=20)),
                ('departamento', models.CharField(blank=True, help_text='Departamento para usuarios externos (Marketing, Tópico, etc.)', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, help_text='Área asignada (NULL para administradores y externos)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Ej: SP, AN', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='productos.campus')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['campus', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pabellon',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pabellones', to='productos.sede'),
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_item', to='productos.area')),
            ],
            options={
                'verbose_name': 'Tipo de Ítem',
                'verbose_name_plural': 'Tipos de Ítem',
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='productos.tipoitem'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['item', 'fecha_solicitud'], name='productos_m_item_id_f66efb_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='productos_m_estado_378504_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['autorizado_por', 'estado'], name='productos_m_autoriz_330a72_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='productos_n_usuario_983ecf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ambiente',
            unique_together={('pabellon', 'piso', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='sede',
            unique_together={('campus', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='pabellon',
            unique_together={('sede', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoitem',
            unique_together={('nombre', 'area')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['codigo_utp'], name='productos_i_codigo__0d4d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['serie'], name='productos_i_serie_e10254_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['area', 'estado'], name='productos_i_area_id_a6feaf_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['ambiente'], name='productos_i_ambient_d0e2d9_idx'),
        ),
    ]
