# Generated by Django 6.0.1 on 2026-01-09 05:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_normalized_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(help_text='RUC del proveedor', max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contacto', models.CharField(blank=True, help_text='Nombre del contacto', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del contrato', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('anulado', 'Anulado'), ('en_proceso', 'En Proceso')], default='vigente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato directo (si no pertenece a un lote)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_directos', to='productos.contrato'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(blank=True, help_text='Código asignado por la institución', max_length=50)),
                ('codigo_interno', models.CharField(editable=False, help_text='Código autogenerado (LOT-YYYY-XXXX)', max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_adquisicion', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='productos.contrato')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote al que pertenece el ítem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='productos.lote'),
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anexo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('monto_modificacion', models.DecimalField(decimal_places=2, default=0, help_text='Monto que modifica al contrato (puede ser positivo o negativo)', max_digits=14)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='productos.contrato')),
            ],
            options={
                'verbose_name': 'Anexo de Contrato',
                'verbose_name_plural': 'Anexos de Contrato',
                'ordering': ['contrato', 'fecha'],
                'unique_together': {('contrato', 'numero_anexo')},
            },
        ),
    ]
