# Generated by Django 4.2.27 on 2026-01-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productos", "0003_cambiar_codigo_utp_a_codigo_interno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("preventivo", "Preventivo"), ("correctivo", "Correctivo")],
                        help_text="Tipo de mantenimiento",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        help_text="Estado actual del mantenimiento",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateField(help_text="Fecha en que se programa el mantenimiento"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que inició el mantenimiento",
                        null=True,
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que finalizó el mantenimiento",
                        null=True,
                    ),
                ),
                (
                    "descripcion_problema",
                    models.TextField(
                        blank=True, help_text="Descripción del problema o motivo del mantenimiento"
                    ),
                ),
                (
                    "trabajo_realizado",
                    models.TextField(blank=True, help_text="Descripción del trabajo realizado"),
                ),
                (
                    "tecnico_asignado",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del técnico que realizó el mantenimiento (puede ser externo)",
                        max_length=150,
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo del mantenimiento",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "proveedor_servicio",
                    models.CharField(
                        blank=True,
                        help_text="Proveedor del servicio de mantenimiento",
                        max_length=200,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reparado", "Reparado"),
                            ("reemplazado", "Reemplazado"),
                            ("no_reparable", "No Reparable"),
                            ("enviado_servicio_externo", "Enviado a Servicio Externo"),
                        ],
                        help_text="Resultado del mantenimiento",
                        max_length=30,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, help_text="Observaciones adicionales"),
                ),
                (
                    "proximo_mantenimiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha programada para el próximo mantenimiento preventivo",
                        null=True,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="productos_i_codigo__60a742_idx",
            old_name="productos_i_codigo__idx",
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mantenimientos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="item",
            field=models.ForeignKey(
                help_text="Ítem al que se le realizará el mantenimiento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mantenimientos",
                to="productos.item",
            ),
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="responsable",
            field=models.ForeignKey(
                help_text="Usuario responsable del mantenimiento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mantenimientos_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="mantenimiento",
            index=models.Index(fields=["item", "estado"], name="productos_m_item_id_52049d_idx"),
        ),
        migrations.AddIndex(
            model_name="mantenimiento",
            index=models.Index(fields=["fecha_programada"], name="productos_m_fecha_p_fa7b1e_idx"),
        ),
        migrations.AddIndex(
            model_name="mantenimiento",
            index=models.Index(fields=["tipo", "estado"], name="productos_m_tipo_2eb8f6_idx"),
        ),
    ]
