# Generated by Django 6.0.1 on 2026-01-29 08:50

import django.core.validators
import django.db.models.deletion
import productos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_update_ubicacion_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(editable=False, help_text='Número autogenerado (ENTREGA-2026-0001)', max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega'), ('devolucion', 'Devolución')], max_length=15)),
                ('ticket', models.CharField(blank=True, help_text='Número de ticket de Mesa de Ayuda (opcional)', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('firma_receptor', models.ImageField(help_text='Firma del colaborador que recibe/devuelve', upload_to='actas/firmas/%Y/%m/')),
                ('firma_emisor', models.ImageField(help_text='Firma del usuario que genera el acta', upload_to='actas/firmas/%Y/%m/')),
                ('pdf_archivo', models.FileField(blank=True, help_text='PDF del acta generada', upload_to='actas/pdf/%Y/%m/')),
                ('correo_enviado', models.BooleanField(default=False)),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Acta de Entrega',
                'verbose_name_plural': 'Actas de Entrega',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ActaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto del equipo (se convierte a WebP)', upload_to='actas/fotos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la foto', max_length=200)),
            ],
            options={
                'verbose_name': 'Foto del Acta',
                'verbose_name_plural': 'Fotos del Acta',
            },
        ),
        migrations.CreateModel(
            name='ActaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_cargador', models.BooleanField(default=False, verbose_name='Cargador/Cables')),
                ('acc_cable_seguridad', models.BooleanField(default=False, verbose_name='Cable de seguridad')),
                ('acc_bateria', models.BooleanField(default=False, verbose_name='Batería')),
                ('acc_maletin', models.BooleanField(default=False, verbose_name='Maletín')),
                ('acc_cable_red', models.BooleanField(default=False, verbose_name='Cable de red')),
                ('acc_teclado_mouse', models.BooleanField(default=False, verbose_name='Teclado y Mouse')),
            ],
            options={
                'verbose_name': 'Ítem del Acta',
                'verbose_name_plural': 'Ítems del Acta',
            },
        ),
        migrations.CreateModel(
            name='ActaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Software del Acta',
                'verbose_name_plural': 'Software del Acta',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='DNI del colaborador (para búsqueda rápida)', max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cargo', models.CharField(help_text='Ej: Coordinador Académico, Enfermero, Director', max_length=100)),
                ('anexo', models.CharField(blank=True, help_text='Anexo o RPE (teléfono corporativo)', max_length=20)),
                ('correo', models.EmailField(help_text='Correo para envío de actas', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de Equipo',
                'verbose_name_plural': 'Marcas de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipos',
                'ordering': ['marca__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_item_destino', models.CharField(blank=True, choices=[('backup', 'Backup'), ('custodia', 'En Custodia'), ('instalado', 'Instalado'), ('garantia', 'En Garantía'), ('mantenimiento', 'En Mantenimiento'), ('transito', 'En Tránsito'), ('baja', 'Baja')], help_text='Estado final del ítem al ejecutar (si difiere del movimiento)', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas para este ítem')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ítem del Movimiento',
                'verbose_name_plural': 'Ítems del Movimiento',
                'ordering': ['agregado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProcesadorEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_basico', models.BooleanField(default=False, help_text='Si es True, aparece seleccionado por defecto en todas las actas')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el acta')),
            ],
            options={
                'verbose_name': 'Software Estándar',
                'verbose_name_plural': 'Software Estándar',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='productos_m_autoriz_330a72_idx',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='departamento',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ejecutado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que confirmó la ejecución/recepción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_ejecutados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado_item_destino',
            field=models.CharField(blank=True, help_text='Estado final del ítem al ejecutar (instalado, backup, baja, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_devolucion_esperada',
            field=models.DateField(blank=True, help_text='Fecha esperada de devolución (para préstamos)', null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, help_text='Fecha real de devolución', null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_en_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_en_transito',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='item_reemplazo',
            field=models.ForeignKey(blank=True, help_text='Ítem que entra como reemplazo (temporal o definitivo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_reemplazo', to='productos.item'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='reemplazo_es_temporal',
            field=models.BooleanField(default=False, help_text='Si es True, el reemplazo es temporal (mantenimiento/garantía)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus asignado para auxiliares de TI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliares', to='productos.campus'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='campus_asignados',
            field=models.ManyToManyField(blank=True, help_text='Campus asignados para supervisores (pueden supervisar varios)', related_name='supervisores', to='productos.campus'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo. Ej: Lab. Química, Aula Magna', max_length=200),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='piso',
            field=models.IntegerField(help_text='Número de piso (positivo) o sótano (negativo: -1, -2)'),
        ),
        migrations.AlterField(
            model_name='especificacionessistemas',
            name='procesador',
            field=models.CharField(blank=True, help_text='Legacy - usar procesador_equipo', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('backup', 'Backup'), ('custodia', 'En Custodia'), ('instalado', 'Instalado'), ('garantia', 'En Garantía'), ('mantenimiento', 'En Mantenimiento'), ('transito', 'En Tránsito'), ('baja', 'Baja')], default='custodia', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, help_text='Fecha de adquisición del ítem', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de adquisición (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, help_text='[DEPRECADO] Usuario que actualmente tiene asignado el ítem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('en_transito', 'En Tránsito'), ('ejecutado', 'Ejecutado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=25),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='foto_evidencia',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: jpg, jpeg, png, gif, webp. Máximo 5MB.', null=True, upload_to='movimientos/%Y/%m/', validators=[productos.validators.ImageValidator()]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='item',
            field=models.ForeignKey(help_text='Ítem que se mueve/sale', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.item'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('traslado', 'Traslado'), ('asignacion', 'Asignación'), ('prestamo', 'Préstamo'), ('mantenimiento', 'Mantenimiento'), ('garantia', 'Garantía'), ('reemplazo', 'Reemplazo'), ('leasing', 'Devolución Leasing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área asignada (Gerentes ven todo su área en todos los campus)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.area'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('auxiliar', 'Auxiliar de TI'), ('almacen', 'Encargado de Almacén')], default='auxiliar', max_length=20),
        ),
        migrations.AlterField(
            model_name='sede',
            name='codigo',
            field=models.CharField(help_text='Código interno. Ej: SP, AN', max_length=10),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que generó el acta', on_delete=django.db.models.deletion.PROTECT, related_name='actas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actafoto',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='productos.actaentrega'),
        ),
        migrations.AddField(
            model_name='actaitem',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.actaentrega'),
        ),
        migrations.AddField(
            model_name='actaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_items', to='productos.item'),
        ),
        migrations.AddField(
            model_name='actasoftware',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='productos.actaentrega'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sede',
            field=models.ForeignKey(help_text='Sede donde trabaja el colaborador', on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='productos.sede'),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='colaborador',
            field=models.ForeignKey(help_text='Colaborador que recibe o devuelve los equipos', on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='productos.colaborador'),
        ),
        migrations.AddField(
            model_name='item',
            name='colaborador_asignado',
            field=models.ForeignKey(blank=True, help_text='Colaborador que tiene asignado el ítem actualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asignados', to='productos.colaborador'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='colaborador_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_anterior', to='productos.colaborador'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='colaborador_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_nuevo', to='productos.colaborador'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo', 'estado'], name='productos_m_tipo_cdb30a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['aprobado_por', 'estado'], name='productos_m_aprobad_4666e8_idx'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='gerencia',
            field=models.ForeignKey(help_text='Gerencia/Departamento al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='productos.gerencia'),
        ),
        migrations.AddField(
            model_name='especificacionessistemas',
            name='marca_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especificaciones', to='productos.marcaequipo', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='modeloequipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='productos.marcaequipo'),
        ),
        migrations.AddField(
            model_name='especificacionessistemas',
            name='modelo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especificaciones', to='productos.modeloequipo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='movimientoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_item', to='productos.item'),
        ),
        migrations.AddField(
            model_name='movimientoitem',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_movimiento', to='productos.movimiento'),
        ),
        migrations.AddField(
            model_name='especificacionessistemas',
            name='procesador_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especificaciones', to='productos.procesadorequipo', verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='actasoftware',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='productos.softwareestandar'),
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='es_emergencia',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='escalado',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='escalado_a',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='estado_item_anterior',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='estado_item_nuevo',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha_escalamiento',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario_anterior',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario_nuevo',
        ),
        migrations.AlterUniqueTogether(
            name='actaitem',
            unique_together={('acta', 'item')},
        ),
        migrations.AddIndex(
            model_name='actaentrega',
            index=models.Index(fields=['numero_acta'], name='productos_a_numero__f97516_idx'),
        ),
        migrations.AddIndex(
            model_name='actaentrega',
            index=models.Index(fields=['tipo', 'fecha'], name='productos_a_tipo_43b401_idx'),
        ),
        migrations.AddIndex(
            model_name='actaentrega',
            index=models.Index(fields=['colaborador', 'fecha'], name='productos_a_colabor_0b4865_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['dni'], name='productos_c_dni_bf452c_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['nombre_completo'], name='productos_c_nombre__ec6766_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['gerencia', 'activo'], name='productos_c_gerenci_f556c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modeloequipo',
            unique_together={('marca', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='movimientoitem',
            unique_together={('movimiento', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='actasoftware',
            unique_together={('acta', 'software')},
        ),
    ]
