# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_add_movimiento_item_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['colaborador_asignado', 'estado'], name='productos_i_colabor_1edc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['garantia_hasta', 'estado'], name='productos_i_garanti_f06b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tipo_item', 'area'], name='productos_i_tipo_it_6913a0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['estado', '-creado_en'], name='productos_i_estado_375fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['es_leasing', 'leasing_vencimiento'], name='productos_i_es_leas_156ec3_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_utp', 'PENDIENTE'), _negated=True), fields=('codigo_utp',), name='unique_codigo_utp_when_assigned'),
        ),
    ]
