# Generated by Django 6.0.1 on 2026-02-02 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_add_item_indexes_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='movimiento',
            field=models.OneToOneField(blank=True, help_text='Movimiento de asignación/préstamo que generó esta acta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acta_entrega', to='productos.movimiento'),
        ),
    ]
