# Generated by Django 6.0.1 on 2026-02-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_link_acta_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Envío'), ('enviado', 'Enviado al Proveedor'), ('en_revision', 'En Revisión'), ('reparado', 'Reparado'), ('reemplazado', 'Reemplazado'), ('rechazado', 'Garantía Rechazada'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del proceso de garantía', max_length=20)),
                ('tipo_problema', models.CharField(choices=[('hardware', 'Falla de Hardware'), ('software', 'Falla de Software'), ('pantalla', 'Problema de Pantalla'), ('bateria', 'Problema de Batería'), ('teclado', 'Problema de Teclado'), ('disco', 'Problema de Disco'), ('memoria', 'Problema de Memoria'), ('otro', 'Otro')], help_text='Tipo de problema reportado', max_length=20)),
                ('descripcion_problema', models.TextField(help_text='Descripción detallada del problema')),
                ('numero_caso', models.CharField(blank=True, help_text='Número de caso o ticket del proveedor', max_length=100)),
                ('contacto_proveedor', models.CharField(blank=True, help_text='Nombre del contacto en el proveedor', max_length=200)),
                ('fecha_reporte', models.DateField(auto_now_add=True, help_text='Fecha en que se reportó el problema')),
                ('fecha_envio', models.DateField(blank=True, help_text='Fecha de envío al proveedor', null=True)),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha de recepción del equipo reparado/reemplazado', null=True)),
                ('diagnostico_proveedor', models.TextField(blank=True, help_text='Diagnóstico del proveedor')),
                ('solucion_aplicada', models.TextField(blank=True, help_text='Solución aplicada por el proveedor')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo_reemplazo', models.ForeignKey(blank=True, help_text='Si fue reemplazado, el nuevo equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantia_como_reemplazo', to='productos.item')),
                ('item', models.ForeignKey(help_text='Ítem enviado a garantía', on_delete=django.db.models.deletion.CASCADE, related_name='garantias_registro', to='productos.item')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor que atiende la garantía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_atendidas', to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Registro de Garantía',
                'verbose_name_plural': 'Registros de Garantía',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['item', 'estado'], name='productos_g_item_id_40a21c_idx'), models.Index(fields=['fecha_reporte'], name='productos_g_fecha_r_e7b8eb_idx'), models.Index(fields=['estado', 'fecha_envio'], name='productos_g_estado_9eae29_idx')],
            },
        ),
    ]
